### PR TITLE
Jimmy dev weapon break replacement

### PR DESCRIPTION
**Pull request by JimmyC7834**
Added 2-slot inventory logic
Added weapon replacement on pick up
Fixed weapon pooling bugs

### CODE REVIEW

**Review by Teru5244 — COMMENTED** [review]
Nice work on inventory, no problems found in codes.

**Weird collision behavior when testing:** When holding two items and trying to catch a newly 
spawned weapon in the air will cause the weapon to lose collision and gravity.

**Comment by JimmyC7834** [comment]
The mentioned bug was solved but found a new bug of multiple collision detection due to improper logic between the projectile script and the pickable script. 
Need to rewrite the logic, should patch on new branch after this merge.

**Review by Teru5244 — COMMENTED** [review]
Did you fix the weapon-dropping bug? I'm still seeing the same bug happening in this branch

**Comment by JimmyC7834** [comment]
@Teru5244 The bug is fixed, I think that's another bug. I just pushed a quick fix and the bug should be gone now.

**Review by Teru5244 — APPROVED** [review]

**Pull request merged**
