### PR TITLE
Rhys weapons after combat patch

### PR DESCRIPTION
**Pull request by rhyswe**
Added spear and bat functionality in prefabs and weapon scripts.

### CODE REVIEW

**Review by JimmyC7834 — APPROVED** [review]
Very good job.

**Comment by Fettuchoony** [comment]
I also experienced the acceleration issues that Pheonix noted. Try adding some friction with the ground or something to solve it? Also the knockback knocks you forward, but that should just be a sign change. Other than that it looks good.

**Review by Teru5244 — CHANGES_REQUESTED** [review]
Please add all weapons to the dataset, and change all the weapons' script fields, some fields are wrong making all of them malfunction.

**Review by Teru5244 — APPROVED** [review]

**Review by JimmyC7834 — APPROVED** [review]
Not working perfectly. I will fix it in new branch

**Pull request merged**
