### PR TITLE
Todd dev fixed animations

### PR DESCRIPTION
**Pull request by Fettuchoony**
The animator script and system is finally up and running without bugs! (That I know of)
TODO: Adjust animation lengths and such to make it look really smooth but that can come later when we have more of a more cemented idea of what we want the visuals to look like.

### CODE REVIEW

**Comment by Fettuchoony** [comment]
Okay I fixed the UserSettings thing I think

**Review by JimmyC7834 — CHANGES_REQUESTED** [review]
@Fettuchoony The animator is finally working!
Tho remember to separate out the visual of the player into its child object.
And also scale up the visual as needed

**Comment by Fettuchoony** [comment]
Merge conflicts are fixed its ready for a final PR

**Review by Teru5244 — COMMENTED** [review]
When the player faces right the weapon does not move to the intended position, is that something you forget to implement?

**Review by JimmyC7834 — APPROVED** [review]
Walking animation is unnoticeable, it needs to remake in a new branch.

**Review by Teru5244 — APPROVED** [review]

**Pull request merged**
