### PR TITLE
Todd dev implement weapon rotation

### PR DESCRIPTION
**Pull request by Fettuchoony**
Added/changed:

- Weapon Rotation
- Recoil values for weapon prefabs (Sniper, Shotgun, Pistol, SMG)
- Added base.Update() to SMG script to call recoil update from UsableItem

IMPORTANT NOTE:
Because the recoil operates in the UsableItem class for use on all usable items, the recoild update will be overridden by any parent Update() methods created. Thus, if you call Update in a gun class, base.Update() must be added in so that the parents update method for the recoil is called. TLDR: put base.Update() in Update methods for individual weapons if you have one.

TODO:
- Add and adjust values for future/ present weapons
- Add new sprites to prefabs, make sure they are under "Visual" GameObject in prefab

### CODE REVIEW

**Comment by Fettuchoony** [comment]
Just realized I pushed a bunch of art we are not going to use anymore, working on removing it right now

**Comment by JimmyC7834** [comment]
The dagger needs some value adjustment so it seems like it's attacking the front but that's a small problem.
The bow's recoil behavior is weird, please check it out.

**Comment by Fettuchoony** [comment]
Fixed the bug where the rotating made the gun recoil the wrong way. Also added support for negative recoil to get the melee effect. WARNING: too much negative recoil with a low tilt speed will cause rotation values to wrap around and get really funky looking.

**Comment by JimmyC7834** [comment]
@Fettuchoony It seems like the fix is not pushed. Please check it out.

**Review by Teru5244 — APPROVED** [review]

**Pull request merged**
